# Love and lonlinnes (June - August) {#love}

## 2014-06-01 From Sara

## 2014-06-04 To Sara

## 2014-06-10 From Tomás

## 2014-06-10 To Mar

## 2014-06-13 To Laura

## 2014-06-20 From Silvia

## 2014-06-21 To Silvia

## 2014-06-22 From Paloma

## 2014-06-22 From Silvia

## 2014-07-02 To Sergio

## 2014-07-08 To Agnese

## 2014-07-13 To ??

## 2014-07-13 To Viki (Farewell)

## 2014-07-15 To Viki

## 2014-07-16 From Viki

## 2014-07-17 To Ana Cantarranas

## 2014-07-17 To Paloma

## 2014-07-17 To Sheila

## 2014-07-17 To Tomás

## 2014-07-17 To Viki

## 2014-07-18 From Sheila

## 2014-07-18 To Viki

## 2014-07-18 To Viki (unsent)

Leuven 18th of August, 2014
 
Viki, you are now just ink on the paper. There is an amazing blond guy of 2 years old and a half.


He is discovering life.


He smiles, he laughs. It’s wonderful.


Knowing. Everything is new. Llama, es listo. Lo sabe todo sin saber. Oye sin oir. Siente sin sentir. Se ríe. Observa. Aprende. Comunica con la cara.


## 2014-07-23 To Viki

## 2014-07-25 From Tomás

## 2014-07-26 To Viki

## 2014-07-27 To Sheila

## 2014-07-27 To Tomás

## 2014-07-28 To Viki

## 2014-07-30 To Javier/Antoñin

## 2014-07-31 To Viki

## 2014-08-08 To Lucía

## 2014-08-09 To Viki

## 2014-08-16 From my GrandMother

## 2014-08-23 To Tom Tom and co.

## 2014-08-23 To Viki

## 2014-08-27 To my GrandMother

## 2014-08-28 To Carlos

## 2014-08-28 Gratitude template

## 2014-08-28 To Danikas (Gratitude)

## 2014-08-28 To Lucía (Gratitude)

## 2014-08-28 To Sergio (Gratitude)

## 2014-08-29 To Silvia (Gratitude)

## 2014-08-29 To Paloma (Gratitude)

## 2014-08-29 To Teleco?

## 2014-08-29 To Tom Tom and Petra (Gratitude)

## 2014-08-29 To Petra and Tom Tom

## 2014-08-30 To Viki

Leuven 30th of August, 2014
 
This is not a postcard, this is an SMS. Yesterday I smoked weed with Teleco and Rober, I will let you know the whole experience one day. Today, I just want to say that there was a moment yesterday that Roberto asked to me.

 
-For you, what is your first pleasure?


Almost automatically, I answered:

-Making people happy (Hacer a la gente feliz)
 
Carlito Fluito,
 
Have a nice day




